In [1]:
#Write a Python program through the following steps:
#1. Create a list variable, names, which contains the names of three of your friends.
#2. Create a Numpy array, ages, that contains the ages of your friends in the same order that you entered their names in names variable.
#3. Use np.random to create a 1-by-3 array of random numbers, and store it in variable rnd.
#4. Find the index (position) of the maximum value of rnd and store it in a variable named max_rnd.
#5. Change the element of names in the position max_rnd to your name, and the element of ages in the position max_rnd to your age.

In [2]:
#step 1

import numpy as np
names = ['Anna', 'Stan', 'Sarah']

In [3]:
#step 2

ages = np.array([25, 45, 37])
print(ages)
print(type(ages))

[25 45 37]
<class 'numpy.ndarray'>


In [4]:
#step 3

rnd = np.random.random(3)
print(rnd)

[0.14971169 0.07306757 0.65097602]


In [5]:
#step 4

largest = np.max(rnd)
print(largest)
position = np.where(rnd == largest)
print(position)
max_rnd = position[0][0]
print(max_rnd)

0.6509760194559157
(array([2], dtype=int64),)
2


In [6]:
#step 5

names[max_rnd] = "Maliheh"
ages[max_rnd] = 38
print(names, ages)

['Anna', 'Stan', 'Maliheh'] [25 45 38]
